name: 'Documentation'

on: [pull]  # Triggers on push

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2

      - name: 'Doxygen html'
        uses: mattnotmitt/doxygen-action@v1.1.0  # pre-build doxygen-action
        with:
          doxyfile-path: "./doxygen"
          working-directory: "."

        - name: 'Deploy'
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./doxygen_documentation/html
