name: 'Documentation'

on:
  pull_request:
    branches: [development]  # Triggers on pull-request

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2

      - name: 'Doxygen html'
        uses: mattnotmitt/config-action@v1.1.0  # pre-build config-action
        with:
          doxyfile-path: "./config"
          working-directory: "."

        - name: 'Deploy'
            uses: peaceiris/actions-gh-pages@v3  # pre-build deployment-action
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./doxygen_documentation/html