# This is a basic original to help you get started with Actions

name: Doxygen Documentation

# Controls when the original will run
on:
  # Triggers the original on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this original manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy_doxy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Build doxyfile'
        uses: mattnotmitt/doxygen-action@v1.3.1  # action to build config documentation from the specified config config file
        with:
          working-directory: "."
          doxyfile-path: "doxygen/config"

      - name: 'Deploy'
        uses: peaceiris/actions-gh-pages@v3.8.0  # pre-build deployment-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen/html
